// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE91D-gAL0ehDeZQbvrtXfHem2lIniQ1k',
    appId: '1:386320270057:android:51f4eb49540d0b1fcc2678',
    messagingSenderId: '386320270057',
    projectId: 'exson-bank',
    databaseURL: 'https://exson-bank-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'exson-bank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGj0Z8YL3x1LmHsuki3hZVz4h8EkboEVk',
    appId: '1:386320270057:ios:5286d66a6373dcd0cc2678',
    messagingSenderId: '386320270057',
    projectId: 'exson-bank',
    databaseURL: 'https://exson-bank-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'exson-bank.appspot.com',
    androidClientId: '386320270057-mhqhsb92um2rjqqrkm28buqgm239ega0.apps.googleusercontent.com',
    iosClientId: '386320270057-j1qpntitm43ecn7om4b3c80ejhn4c87j.apps.googleusercontent.com',
    iosBundleId: 'uz.exson',
  );

}